In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt


In [6]:
data = pd.read_csv("/kaggle/input/digit-recognizer/train.csv")
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

In [9]:
data_d = data[0: 1000].T
Y_d = data_d[0]
X_d = data_d[1:n]
X_d = X_d/255.
data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train/255.
_,m_train = X_train.shape


In [49]:
def init_paras():
    W1 = np.random.rand(10, 784)
    b1 = np.random.rand(10, 1)
    W2 = np.random.rand(10, 10)
    b2 = np.random.rand(10, 1)
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    Z_shifted = Z - np.max(Z)
    A = np.exp(Z_shifted) / np.sum(np.exp(Z_shifted))
    return A

def forward_propagation(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z>0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_propagation(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    DZ2 = A2 - one_hot_Y
    DW2 = 1/m*DZ2.dot(A1.T)
    Db2 = 1/m*np.sum(DZ2)
    DZ1 = W2.T.dot(DZ2)* ReLU_deriv(Z1)
    DW1 = 1/m*DZ1.dot(X.T)
    Db1 = 1/m*np.sum(DZ1)
    return DW1, Db1, DW2, Db2

def update_paras(W1, b1, W2, b2, DW1, Db1, DW2, Db2, alpha):
    W1 = W1 -alpha*DW1
    b1 = b1 - alpha*Db1
    W2 = W2 - alpha*DW2
    b2 = b2 - alpha*Db2
    return W1, b1, W2, b2

In [50]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y)/Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_paras()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_propagation(W1, b1, W2, b2, X)
        DW1, Db1, DW2, Db2 = backward_propagation(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_paras(W1, b1, W2, b2, DW1, Db1, DW2, Db2, alpha)
        if i% 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))

    return W1, b1, W2, b2
        

In [51]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.1, 490)

Iteration:  0
[1 1 1 ... 1 0 1] [3 0 4 ... 5 1 4]
0.01648780487804878
Iteration:  10
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09807317073170732
Iteration:  20
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09807317073170732
Iteration:  30
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09807317073170732
Iteration:  40
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09804878048780488
Iteration:  50
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09804878048780488
Iteration:  60
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09804878048780488
Iteration:  70
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09804878048780488
Iteration:  80
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09804878048780488
Iteration:  90
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09804878048780488
Iteration:  100
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09804878048780488
Iteration:  110
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09804878048780488
Iteration:  120
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09804878048780488
Iteration:  130
[0 0 0 ... 0 0 0] [3 0 4 ... 5 1 4]
0.09804878048780488
Ite